Update guidelines to reflect the new Graphistry version
graphistry/graphistry-cli pull request #44
Opened 2024-07-12 01:48 UTC by aucahuasi

- Update CUDA 11.5 to CUDA 11.8
- Update ubuntu 20.04 to ubuntu 22.04
- Update RAPIDS version (23.10) and new docker conventions (conda env).

2024-07-12 02:09 UTC, DataBoyTX requested changes
I think there's one file for the setup scripts that you might have overlooked: https://github.com/graphistry/graphistry-cli/blob/a6fcc76f5af420903d4d406e06f97aca5ce0235a/docs/ubuntu_20_04_setup.sh#L299

but other than that, LGTM!

2024-07-12 16:31 UTC, aucahuasi commented
> 11.0.3

Good catch, thanks Thomas! Solved!

2024-07-17 01:21 UTC, lmeyerov approved these changes

2024-07-17 01:22 UTC, lmeyerov commented
Looks good - let's merge when the new release goes out

2024-07-19 01:31 UTC, lmeyerov commented on docs/azure_marketplace.md
> +Users may override the default setting and enable GDS support manually by setting the environment variable in the `data/config/custom.env` file (a Docker Compose environment file). For example: `LIBC
also add to `azure.md` that users most explicitly set `LIBCUDF_CUFILE_POLICY=OFF` as well, e.g., would happen if someone uses the tarball or AKS

2024-10-28 01:07 UTC, merged